### ISSUE TITLE
Unusual scrollbar positioning

### ISSUE THREAD

**Issue by jonsmithers** [PolymerElements/paper-dialog-behavior#100]
### Description

When a paper-dialog contains a scrollable div which contains a paper-input, the scrollable div has unusual scrollbar placement.

### Expected outcome

The scrollbar should appear along the scrollable div's border.

### Actual outcome

The scrollbar appears left of where it should be.

### Live Demo

https://jonsmithers.github.io/bug-demonstration/

### Steps to reproduce

1. Put a scrollable div inside a paper-dialog
2. Put a paper-input inside the scrollable div
3. Open page in Chrome on mobile

### Browsers Affected
- [x] Chrome (**mobile only**)
- [ ] Firefox

I wasn't able to determine the actual culprit for this behavior, so I apologize if this is posted in the wrong repo.

| Firefox (no issue) | Chrome | 
| ----- | ---- |
| ![screenshot_20160918-151123](https://cloud.githubusercontent.com/assets/2660313/18618319/5b1f8bd2-7db2-11e6-8a27-95ae85a00fb5.png) | ![screenshot_20160918-151059](https://cloud.githubusercontent.com/assets/2660313/18618321/5ce495ac-7db2-11e6-937f-abd04882414b.png) |

**Comment by valdrinkoshi** [comment]
Hi @jonsmithers, this is a bug of chrome wrongly rendering scrollbars on retina displays, please see https://bugs.chromium.org/p/chromium/issues/detail?id=581136

**Comment by jonsmithers** [comment]
@valdrinkoshi Ah, thanks!
