### ISSUE TITLE
errors raised in _onDialogClick function for removed elements actioned by click event.

### ISSUE THREAD

**Issue by ghawkins-pulsemining** [PolymerElements/paper-dialog-behavior#14]
Hi,

Only a minor issue, but i have been testing a kendo multiselect in my app, and works fine, other than clicking on a selection tag to remove the tag element. It works, but the following error is thrown in the console:
```
Uncaught TypeError: Cannot read property 'hasAttribute' of null
```
Am guessing that this is due to the element being deleted and the event still bubbling up (and is not specifically a kendo widget issue, i would assume that the same would happen if a polymer element is removed via click event and the event propogates). I know this is not actually really a polymer bug, and i could stop the event from propagating up after the tag is deleted in the kendo multiselect widget, but the function _onDialogClick can be modified fairly easily to make it a little more robust.....
Current Function:
```
_onDialogClick: function(event) {
      var target = event.target;
      while (target !== this) {
        if (target.hasAttribute('dialog-dismiss')) {
          this._updateClosingReasonConfirmed(false);
          this.close();
          break;
        } else if (target.hasAttribute('dialog-confirm')) {
          this._updateClosingReasonConfirmed(true);
          this.close();
          break;
        }
        target = target.parentNode;
      }
    }
```

suggested addition to the while conditions as below to make sure that target is still a valid object.
```
_onDialogClick: function(event) {
      var target = event.target;
      while (target && target !== this) {
        if (target.hasAttribute('dialog-dismiss')) {
          this._updateClosingReasonConfirmed(false);
          this.close();
          break;
        } else if (target.hasAttribute('dialog-confirm')) {
          this._updateClosingReasonConfirmed(true);
          this.close();
          break;
        }
        target = target.parentNode;
      }
    }
```
Have tested this code change for this scenario and is working for me, although i have not ventured through other testing scenarios (I can't see this as a breaking change though).
Am fairly green to the whole process so am after feedback on this sort of thing, should i be just doing the change and submitting a pull request or do we like to discuss things first here? :)

Many thanks,
Grant.

**Comment by ghawkins-pulsemining** [comment]
just looking further into this, it appears that the parent node is deleted but the child nodes are left orphaned, which isn't great but is possible.... the loop is working its way through the orphaned elements until it get to the deleted parent and throws the error... 
This code section is a simple console.log("target:", target); in the first line of the while loop...
```
target: <span unselectable=​"on" class=​"k-icon k-i-close">​delete​</span> ​paper-dialog-behavior.html:178
target: <span unselectable=​"on" class=​"k-select">​…​</span>​ paper-dialog-behavior.html:178
target: <li class=​"k-button k-state-hover" unselectable=​"on">​…​</li>​ paper-dialog-behavior.html:178
target: null
```
Orphans probably shouldn't exist but the test for valid target still makes it work more robustly.

Thanks,
Grant.

**Comment by morethanreal** [comment]
This seems like a reasonable fix to me. Can you submit a PR with a code comment and test case?

**Comment by codegist** [comment]
I'm having a similar issue, but it's not to do with null reference, but where target happens to be a #document-fragment and such as, doesn't have hasAttribute method at all. I'd check for existance of method as well

**Comment by morethanreal** [comment]
Fixed in https://github.com/PolymerElements/paper-dialog-behavior/pull/17
