### ISSUE TITLE
Could not open paper-dialog with touch screen (like in Mobile App [cordova, CCA])

### ISSUE THREAD

**Issue by jmorille** [PolymerElements/paper-dialog-behavior#19]
If you use the dialog on mobile with touch screen, 

1* When you click on the button , the button event could reach the function that do the this.$.myDialog.open(), and the dialog open well
 2* but the touch event (outside the dialog) was immediately raise that produce the close  of the dialog.

In practice it not usable possible to use this component with touch screen.

A work around could be used a modal options on paper-dialog but that do not work because in this case, it not possible to click in the dialog. The modal, block everything including the dialog.
I have to open an ticket also for the modal options.

**Comment by valdrinkoshi** [comment]
Hi @jmorille, could you provide a snippet of code to reproduce this?
Here a test app with a dialog that is being toggled through a button:
![cordova](https://cloud.githubusercontent.com/assets/6173664/11903983/fc9af178-a571-11e5-8e80-274cb4b6ea88.gif)

**Comment by notwaldorf** [comment]
This issue looks inactive. Please re-open it if it's still occurring.
