### ISSUE TITLE
modal dialog steals focus from distributed content in child elements

### ISSUE THREAD

**Issue by bendavis78** [PolymerElements/paper-dialog-behavior#20]
It's tough to explain this one without an example: https://jsbin.com/mahiwo/edit?html,output

In this example we have a `form-dialog` element which can be wrapped around a set of fields to present as a dialog. It contains a `paper-dialog` in its shadowdom. As you can see, you can't edit the field, and as soon as it gains focus, it's impossible get it back to a blurred state.

I've found this only happens when shadow dom is enabled.

**Comment by bendavis78** [comment]
After researching this more, I now understand why it's happening. The dialog behavior explicitly prevents the focus event from occurring on nodes that are not children of itself. It does this by traversing the ancestors of the target element, and checks whether or not it is a direct ancestor. The problem is that it is not considering *composed* DOM. If an element exists outside of the dialog and is composed into an element inside the dialog, parentNode traversal doesn't detect it as a child.

If there was native way to traverse composed DOM, we'd have a simple solution, but I don't think there is. I think the only real option may be to just document the fact that `<content>` tags inside a dialog should not select elements from outside the dialog. Perhaps `paper-dialog-behavior` could raise a warning if it detects that.

**Comment by valdrinkoshi** [comment]
This got fixed in https://github.com/PolymerElements/paper-dialog-behavior/pull/58
`Polymer.dom(event).path` has been recently updated to work properly with destination insertion points (https://github.com/Polymer/polymer/pull/3202) and will be available in `v1.2.4`.
