### ISSUE TITLE
please fix encoding in this file paper-dialog-common.css

### ISSUE THREAD

**Issue by triune** [PolymerElements/paper-dialog-behavior#27]
Chrome always complains in the console...
Resource interpreted as Document but transferred with MIME type text/css: "https://dev.g.x/assets/bower_components/paper-dialog-behavior/paper-dialog-common.css".

**Comment by abdonrd** [comment]
The #34 fix the problem. :smile:

**Comment by triune** [comment]
Warning msg still seems to persist today even after latest bower update of all components.

**Comment by abdonrd** [comment]
@triune the Polymer team has not yet accepted the #34.

**Comment by triune** [comment]
@abdonrd Thanks, I think I understand the commit -> bower path a little better now :+1:

**Comment by valdrinkoshi** [comment]
Closing this, feel free to re-open if the issue persists
