### ISSUE TITLE
Closing nested dialog close all dialog parents

### ISSUE THREAD

**Issue by wicksell** [PolymerElements/paper-dialog-behavior#31]
Clicking an element with dialog-dismiss or dialog-confirm attribute close all levels of nested dialogs.

The problem is in Polymer.PaperDialogBehaviorImpl._onDialogClick. The method must check that the event target do not have any closer element implementing Polymer.PaperDialogBehavior.

Something like this:

    _onDialogClick: function(event) {
      var target = event.target;
      while (target && target !== this) {
        if (target.hasAttribute) {
          if (target.hasAttribute('dialog-dismiss') && this._getClosestDialog(target) === this) {
            this._updateClosingReasonConfirmed(false);
            this.close();
            break;
          } else if (target.hasAttribute('dialog-confirm') && this._getClosestDialog(target) === this) {
            this._updateClosingReasonConfirmed(true);
            this.close();
            break;
          }
        }
        target = target.parentNode;
      }
    },

    // Find closest dialog parent of an element. We should really find the closest element
    // implementing Polymer.PaperDialogBehavior, how do we do that?
    _getClosestDialog: function(element) {
        while (element !== null) {
            if (element.nodeName == "PAPER-DIALOG") {
                return element;
            }
            element = element.parentElement;
        }

    },

**Comment by jtakacs** [comment]
I had the same issue with nested `paper-dialog`s, and @wicksell 's solution worked for me.

**Comment by valdrinkoshi** [comment]
This gets fixed by stopping the event's propagation ;)
