### ISSUE TITLE
Paper-dialog not centered when opened

### ISSUE THREAD

**Issue by rvraaphorst** [PolymerElements/paper-dialog-behavior#41]
As mentioned in the paper-dialog issues (https://github.com/PolymerElements/paper-dialog/issues/36), a (modal) paper-dialog is not centered when opened but slightly off to the right and the bottom. That behaviour is coded in the paper-dialog-behaviour element however.
(Also see http://stackoverflow.com/questions/33650752/center-paper-dialog-upon-opening)

**Comment by valdrinkoshi** [comment]
This is an issue of `IronOverlayBehavior`, which triggers the positioning calculation too early (on `ready`).
Instead, this should be done on `attached`. Tracking the issue here https://github.com/PolymerElements/iron-overlay-behavior/issues/60
Closing this as is a duplicate
