### ISSUE TITLE
Merge paper-dialog-behavior into paper-dialog

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-dialog-behavior#45]
Why two separate elements?

I think that we can merge the `paper-dialog-behavior` into `paper-dialog`.

What do you think?

**Comment by notwaldorf** [comment]
Generally, we want to keep all behaviours as separate repos, so that you don't need to download all the behaviour to just use a dialog. It's unlikely that this is a change that we'd go forward with.

/cc @cdata

**Comment by abdonrd** [comment]
I understand it.

But I personally think it would be better to hold it together. I understand that the `iron-elements` behaviors are separated, as they must have very generic behaviors. But in the case of `paper-elements`, they are very particular, as they are to follow the guide material design.

And if we only use the behavior, we can download the `paper-dialog` and only import only the 'paper-dialog-behavior.html`.

**Comment by dantman** [comment]
You mean `paper-dialog`, right? Not `paper-behavior`.

**Comment by abdonrd** [comment]
@dantman right!

**Comment by abdonrd** [comment]
As far as I know, the Polymer Elements are not going to continue developing. So I close this issue.
