### ISSUE TITLE
MMMoooaaarrr style for paper-dialog-button

### ISSUE THREAD

**Issue by MeTaNoV** [PolymerElements/paper-dialog-behavior#49]
Hi,
currently, it is only possible to apply a custom property to the buttons of a dialog via `--paper-dialog-button-color`.
It would be nice either to have an additional custom property for the background like `--paper-dialog-button-background-color` or better a more general mixin like `--paper-dialog-button`.
Cheers,
Pascal

**Comment by notwaldorf** [comment]
Hmm, the buttons are in your light DOM, so you should be able to style them as you wish. Here is a demo of that: http://jsbin.com/qehabas/edit?html,output

**Comment by MeTaNoV** [comment]
I don't want to style it at this level, I have a theming constraint so that I have to use custom property and/or mixin to access it. This is what they are meant for! :)

**Comment by MeTaNoV** [comment]
And this is not a breakin change this time, only a small upgrade! :D

**Comment by notwaldorf** [comment]
You can do this by applying a mixin to the `paper-buttons` inside the `paper-dialog`, and then define this mixin the `n` levels up where you actually want it:

In the place where you're actually adding the `paper-buttons` to the `paper-dialog`,
```css
paper-dialog > paper-button {
  @apply(--custom-paper-button-inside-dialog);
  // or you can use --paper-button: var(--custom-paper-button-inside-dialog);
}
```
And wherever you're doing your styling,
```
  --custom-paper-button-inside-dialog: {...};
```

**Comment by MeTaNoV** [comment]
This is overkill... I mean, why does `--paper-dialog-button-color` exist in `paper-dialog-behavior` then? and all others when I can define my own mixin like you describe? You propose my a workaround I would like to avoid.

**Comment by MeTaNoV** [comment]
Moreover, in my case, I have 2 different dialogs to work with, so I'll have to apply your workaround twice unnecessarily and you could imagine some case with n dialogs... Do you want me to do the code and create the PR if it is more time efficient for you? Ping @hickscorp

**Comment by hickscorp** [comment]
I'd agree that the API seems a bit inconsistent here. IMO, if it would become too cumbersome to expose all properties (`--paper-dialog-button-background-color`), at least a `--paper-dialog-button` generic one would be a good idea.

What determines what would be exposed as a mixin and what's not? Are there any guidelines around that I'm not aware of?

**Comment by cdata** [comment]
> I don't want to style it at this level, I have a theming constraint so that I have to use custom property and/or mixin to access it. This is what they are meant for! :)

Could you describe this constraint with a reduced test case? This might help us in figuring out the best path forward.

**Comment by MeTaNoV** [comment]
The use-case is pretty simple, I want to theme my app, and among other things I would like to target all dialog buttons. Custom property and mixins are exactly the answer to this use-case, but in the case of `paper-dialog-behavior`, there is a tiny lack that I address through this issue. This is a 2 or 4 liners change including doc w/o breaking change.

**Comment by cdata** [comment]
@MeTaNoV Thanks, my hope is that you can show us a code example, so that we can reason about the limitations you are describing to us. We may be able to propose an alternative approach, or the example may demonstrate to use the need for a change.

**Comment by valdrinkoshi** [comment]
Closing this, @MeTaNoV feel free to re-open with an example (check the [CONTRIBUTING.md](https://github.com/PolymerElements/paper-dialog-behavior/blob/master/CONTRIBUTING.md)

**Comment by MeTaNoV** [comment]
just let it flow... :)
