### ISSUE TITLE
Focus change count test failing in Firefox 43

### ISSUE THREAD

**Issue by cdata** [PolymerElements/paper-dialog-behavior#59]
`AssertionError: focus change count: expected 0 to equal 2 (:0)`

https://travis-ci.org/PolymerElements/paper-dialog-behavior/builds/101732536

**Comment by valdrinkoshi** [comment]
This seems caused by the fact that firefox doesn't trigger focus events if we switch the window focus to another application. To reproduce it locally, run `wct` and make sure to switch window focus with `Command + Tab` (remove the focus from firefox).
