### ISSUE TITLE
Broken Tests - dialog-dismiss button inside a custom element is handled

### ISSUE THREAD

**Issue by chiefcll** [PolymerElements/paper-dialog-behavior#66]
I just pulled down the latest paper-dialog-behavior (v1.1.1) and ran the tests and have 2 failures in chrome. 

dialog-dismiss button inside a custom element is handled
dialog-confirm button inside a custom element is handled

This corresponds to the original issue of why I pulled down the repo. Updating our bower components caused paper-dialog not to close when the parentElement of the click target has the dialog-dismiss attribute.

Is there a build process that is checking stability with all the components?

**Comment by notwaldorf** [comment]
@valdrinkoshi I thiiiiink this may be a repro case (I was going to also open an issue for this) http://jsbin.com/qubemo/edit?html,console,output

**Comment by chiefcll** [comment]
https://travis-ci.org/PolymerElements/paper-dialog-behavior/builds/105760457

Travis is currently failing on the latest.
