### ISSUE TITLE
paper-dialog inside paper-drawer - dialog hidden behind backdrop

### ISSUE THREAD

**Issue by bwh-rl** [PolymerElements/paper-dialog-behavior#78]
http://jsbin.com/zenicodoho/1/edit?html,output

If the paper-dialog is outside of the paper-drawer-panel it works.
But if the content is separated in some kind of content elements the paper-dialog should be included in them.

e.g.
```
<paper-drawer-panel>
  <iron-pages drawer>
    <drawer-element-a></drawer-element-a>
    ....
  </iron-pages>
  ....
<paper-drawer-panel>

<dom-module id="drawer-element-a">
  <template>
    ....
    <paper-dialog>
     ....
    </paper-dialog>
  </template>
<dom-module>
```

**Comment by valdrinkoshi** [comment]
Hi @bwh-rl, please see [this discussion](https://github.com/PolymerElements/paper-dialog/issues/44#issuecomment-172013206) for more details, but in short this is a known problem of when you insert an overlay within an element that creates a new stacking context. The platform doesn't provide ways for overlays to pop out of a stacking context, so it's up to the Polymer user to handle it (e.g. add overlays to body).
Closing this as duplicate.

**Comment by punkratz312** [comment]
still an issue to me
