### ISSUE TITLE
ESC key no longer closes dialog, 1.2.0

### ISSUE THREAD

**Issue by freshp86** [PolymerElements/paper-dialog-behavior#79]
Open modal dialog, hit ESC key. Expected the dialog to close, nothing happens. This used to work for version 1.1.1.

**Comment by valdrinkoshi** [comment]
Hi @freshp86, this was changed as per request in https://github.com/PolymerElements/paper-dialog-behavior/issues/64. A modal dialog will be closed only by clicking on the closing button/calling `close` imperatively. 
`modal` is a shortcut for setting 3 properties at once: `noCancelOnOutsideClick, noCancelOnEscKey, withBackdrop`.
To achieve the previous behavior, you could set `noCancelOnOutsideClick, withBackdrop` without setting `modal`
```html
<paper-dialog no-cancel-on-outside-click with-backdrop></paper-dialog>
```
If you want to set `modal`, you can set `noCancelOnEscKey = false` **after** setting `modal`:
```html
<paper-dialog id="dialog" modal></paper-dialog>
...
ready: function() {
  this.$.dialog.noCancelOnEscKey = false;
}

**Comment by freshp86** [comment]
Thanks for the explanation.
