### ISSUE TITLE
Dialog close events should occur within the scope of the browser event which triggered them.

### ISSUE THREAD

**Issue by peteblois** [PolymerElements/paper-dialog-behavior#99]
### Description
Currently the iron-overlay-closed event is raised from the next requestAnimationFrame after the dialog has closed. This means that the event cannot be used to trigger browser operations which require being called in response to an interactive event (opening a popup, request fullscreen, accessing media, etc).

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by valdrinkoshi** [comment]
Hi @peteblois, you can listen for `opened-changed` which is triggered synchronously when the property `opened` changes. `iron-overlay-closed` is to be used if you want to wait for the overlay to be completely closed.
